version: '1'
services:
  spring-app:
    image: van133/streaming:latest
    container_name: streaming
    ports:
      - "8080:8080"
    volumes:
      - tmp:/tmp
#    restart: unless-stopped


  mysql:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped


  nginx-rtmp:
    image: van133/nginx-rtmp
    ports:
      - "1935:1935"
      - "80:80"
    volumes:
      - tmp:/tmp

volumes:
  tmp: