version: '2'
services:
  spring-app:
    image: van133/streaming:test
    container_name: streaming
    ports:
      - "8080:8080"
    volumes:
      - tmp:/tmp
  #    restart: unless-stopped


  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx-rtmp:
    image: van133/nginx-rtmp:test
    ports:
      - "1935:1935"
      - "80:80"
      - "443:443"
    volumes:
      - tmp:/tmp
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

volumes:
  tmp: